// GENERATED CODE - DO WHATEVER YOU WANT WITH IT
// **************************************************************************
// Total assets: 329
// Generated by flutter_assets_generator extension for VS Code
// @mrasityilmaz
// **************************************************************************


class Assets {

	static const String chart_svg = 'assets/icons/chart.svg';

	static const String home_svg = 'assets/icons/home.svg';

	static const String location_svg = 'assets/icons/location.svg';

	static const String profile_svg = 'assets/icons/profile.svg';

	static const String ascent_png = 'assets/images/Ascent.png';

	static const String atenza_png = 'assets/images/Atenza.png';

	static const String audi_a3_png = 'assets/images/Audi A3.png';

	static const String audi_q3_png = 'assets/images/Audi Q3.png';

	static const String audi_q5_png = 'assets/images/Audi Q5.png';

	static const String audi_q7_png = 'assets/images/Audi Q7.png';

	static const String audi_rs_q8_png = 'assets/images/Audi RS Q8.png';

	static const String audi_tt_png = 'assets/images/Audi TT.png';

	static const String axela_png = 'assets/images/Axela.png';

	static const String b180_png = 'assets/images/B180.png';

	static const String c200_png = 'assets/images/C200.png';

	static const String cx_8_png = 'assets/images/CX 8.png';

	static const String cx3_png = 'assets/images/CX3.png';

	static const String cx5_png = 'assets/images/CX5.png';

	static const String demio_png = 'assets/images/Demio.png';

	static const String e200_png = 'assets/images/E200.png';

	static const String e400_png = 'assets/images/E400.png';

	static const String ellipse_4_jpeg = 'assets/images/ellipse_4.jpeg';

	static const String forester_png = 'assets/images/Forester.png';

	static const String glc_250_png = 'assets/images/GLC 250.png';

	static const String gle_350_png = 'assets/images/GLE 350.png';

	static const String hiace_png = 'assets/images/Hiace.png';

	static const String hilux_png = 'assets/images/Hilux.png';

	static const String icons_8_expensive_price_501_png = 'assets/images/icons_8_expensive_price_501/png';

	static const String icons_8_road_321_png = 'assets/images/icons_8_road_321/png';

	static const String impreza_png = 'assets/images/Impreza/png';

	static const String juke_png = 'assets/images/Juke.png';

	static const String land_cruiser_prado_png = 'assets/images/Land Cruiser Prado.png';

	static const String legacy_png = 'assets/images/Legacy.png';

	static const String mark_x_png = 'assets/images/Mark X.png';

	static const String navara_png = 'assets/images/Navara.png';

	static const String note_png = 'assets/images/Note.png';

	static const String outback_png = 'assets/images/Outback.png';

	static const String rav4_png = 'assets/images/RAV4.png';

	static const String road_052_png = 'assets/images/road_052.png';

	static const String screenshot_202406301537561_jpeg = 'assets/images/screenshot_202406301537561.jpeg';

	static const String teana_png = 'assets/images/Teana.png';

	static const String tesla_car_png_561_png = 'assets/images/tesla_car_png_561.png';

	static const String th_13_png = 'assets/images/th_13.png';

	static const String vitz_png = 'assets/images/Vitz/png';

	static const String wingroad_png = 'assets/images/Wingroad.png';

	static const String wrx_png = 'assets/images/WRX.png';

	static const String x_trail_png = 'assets/images/X-Trail.png';

	static const String arrow_right_x2_svg = 'assets/vectors/arrow_right_x2.svg';

	static const String arrow_uup_left_10_x2_svg = 'assets/vectors/arrow_uup_left_10_x2.svg';

	static const String arrow_uup_left_11_x2_svg = 'assets/vectors/arrow_uup_left_11_x2.svg';

	static const String arrow_uup_left_12_x2_svg = 'assets/vectors/arrow_uup_left_12_x2.svg';

	static const String arrow_uup_left_13_x2_svg = 'assets/vectors/arrow_uup_left_13_x2.svg';

	static const String arrow_uup_left_14_x2_svg = 'assets/vectors/arrow_uup_left_14_x2.svg';

	static const String arrow_uup_left_15_x2_svg = 'assets/vectors/arrow_uup_left_15_x2.svg';

	static const String arrow_uup_left_16_x2_svg = 'assets/vectors/arrow_uup_left_16_x2.svg';

	static const String arrow_uup_left_17_x2_svg = 'assets/vectors/arrow_uup_left_17_x2.svg';

	static const String arrow_uup_left_18_x2_svg = 'assets/vectors/arrow_uup_left_18_x2.svg';

	static const String arrow_uup_left_19_x2_svg = 'assets/vectors/arrow_uup_left_19_x2.svg';

	static const String arrow_uup_left_1_x2_svg = 'assets/vectors/arrow_uup_left_1_x2.svg';

	static const String arrow_uup_left_20_x2_svg = 'assets/vectors/arrow_uup_left_20_x2.svg';

	static const String arrow_uup_left_2_x2_svg = 'assets/vectors/arrow_uup_left_2_x2.svg';

	static const String arrow_uup_left_3_x2_svg = 'assets/vectors/arrow_uup_left_3_x2.svg';

	static const String arrow_uup_left_4_x2_svg = 'assets/vectors/arrow_uup_left_4_x2.svg';

	static const String arrow_uup_left_6_x2_svg = 'assets/vectors/arrow_uup_left_6_x2.svg';

	static const String arrow_uup_left_7_x2_svg = 'assets/vectors/arrow_uup_left_7_x2.svg';

	static const String arrow_uup_left_8_x2_svg = 'assets/vectors/arrow_uup_left_8_x2.svg';

	static const String arrow_uup_left_9_x2_svg = 'assets/vectors/arrow_uup_left_9_x2.svg';

	static const String arrow_uup_left_x2_svg = 'assets/vectors/arrow_uup_left_x2.svg';

	static const String background_1_x2_svg = 'assets/vectors/background_1_x2.svg';

	static const String background_x2_svg = 'assets/vectors/background_x2.svg';

	static const String battery_11_x2_svg = 'assets/vectors/battery_11_x2.svg';

	static const String battery_12_x2_svg = 'assets/vectors/battery_12_x2.svg';

	static const String battery_13_x2_svg = 'assets/vectors/battery_13_x2.svg';

	static const String battery_14_x2_svg = 'assets/vectors/battery_14_x2.svg';

	static const String battery_15_x2_svg = 'assets/vectors/battery_15_x2.svg';

	static const String battery_16_x2_svg = 'assets/vectors/battery_16_x2.svg';

	static const String battery_17_x2_svg = 'assets/vectors/battery_17_x2.svg';

	static const String battery_19_x2_svg = 'assets/vectors/battery_19_x2.svg';

	static const String battery_1_x2_svg = 'assets/vectors/battery_1_x2.svg';

	static const String battery_20_x2_svg = 'assets/vectors/battery_20_x2.svg';

	static const String battery_21_x2_svg = 'assets/vectors/battery_21_x2.svg';

	static const String battery_22_x2_svg = 'assets/vectors/battery_22_x2.svg';

	static const String battery_23_x2_svg = 'assets/vectors/battery_23_x2.svg';

	static const String battery_2_x2_svg = 'assets/vectors/battery_2_x2.svg';

	static const String battery_3_x2_svg = 'assets/vectors/battery_3_x2.svg';

	static const String battery_4_x2_svg = 'assets/vectors/battery_4_x2.svg';

	static const String battery_5_x2_svg = 'assets/vectors/battery_5_x2.svg';

	static const String battery_6_x2_svg = 'assets/vectors/battery_6_x2.svg';

	static const String battery_7_x2_svg = 'assets/vectors/battery_7_x2.svg';

	static const String battery_8_x2_svg = 'assets/vectors/battery_8_x2.svg';

	static const String battery_9_x2_svg = 'assets/vectors/battery_9_x2.svg';

	static const String battery_x2_svg = 'assets/vectors/battery_x2.svg';

	static const String cellular_connection_10_x2_svg = 'assets/vectors/cellular_connection_10_x2.svg';

	static const String cellular_connection_11_x2_svg = 'assets/vectors/cellular_connection_11_x2.svg';

	static const String cellular_connection_12_x2_svg = 'assets/vectors/cellular_connection_12_x2.svg';

	static const String cellular_connection_13_x2_svg = 'assets/vectors/cellular_connection_13_x2.svg';

	static const String cellular_connection_14_x2_svg = 'assets/vectors/cellular_connection_14_x2.svg';

	static const String cellular_connection_15_x2_svg = 'assets/vectors/cellular_connection_15_x2.svg';

	static const String cellular_connection_16_x2_svg = 'assets/vectors/cellular_connection_16_x2.svg';

	static const String cellular_connection_17_x2_svg = 'assets/vectors/cellular_connection_17_x2.svg';

	static const String cellular_connection_18_x2_svg = 'assets/vectors/cellular_connection_18_x2.svg';

	static const String cellular_connection_19_x2_svg = 'assets/vectors/cellular_connection_19_x2.svg';

	static const String cellular_connection_1_x2_svg = 'assets/vectors/cellular_connection_1_x2.svg';

	static const String cellular_connection_20_x2_svg = 'assets/vectors/cellular_connection_20_x2.svg';

	static const String cellular_connection_21_x2_svg = 'assets/vectors/cellular_connection_21_x2.svg';

	static const String cellular_connection_22_x2_svg = 'assets/vectors/cellular_connection_22_x2.svg';

	static const String cellular_connection_2_x2_svg = 'assets/vectors/cellular_connection_2_x2.svg';

	static const String cellular_connection_3_x2_svg = 'assets/vectors/cellular_connection_3_x2.svg';

	static const String cellular_connection_4_x2_svg = 'assets/vectors/cellular_connection_4_x2.svg';

	static const String cellular_connection_5_x2_svg = 'assets/vectors/cellular_connection_5_x2.svg';

	static const String cellular_connection_6_x2_svg = 'assets/vectors/cellular_connection_6_x2.svg';

	static const String cellular_connection_7_x2_svg = 'assets/vectors/cellular_connection_7_x2.svg';

	static const String cellular_connection_9_x2_svg = 'assets/vectors/cellular_connection_9_x2.svg';

	static const String cellular_connection_x2_svg = 'assets/vectors/cellular_connection_x2.svg';

	static const String container_1_x2_svg = 'assets/vectors/container_1_x2.svg';

	static const String container_2_x2_svg = 'assets/vectors/container_2_x2.svg';

	static const String container_x2_svg = 'assets/vectors/container_x2.svg';

	static const String envelope_simple_x2_svg = 'assets/vectors/envelope_simple_x2.svg';

	static const String group_1_x2_svg = 'assets/vectors/group_1_x2.svg';

	static const String group_2_x2_svg = 'assets/vectors/group_2_x2.svg';

	static const String group_3_x2_svg = 'assets/vectors/group_3_x2.svg';

	static const String group_4_x2_svg = 'assets/vectors/group_4_x2.svg';

	static const String group_5_x2_svg = 'assets/vectors/group_5_x2.svg';

	static const String group_6_x2_svg = 'assets/vectors/group_6_x2.svg';

	static const String group_7_x2_svg = 'assets/vectors/group_7_x2.svg';

	static const String group_8_x2_svg = 'assets/vectors/group_8_x2.svg';

	static const String group_x2_svg = 'assets/vectors/group_x2.svg';

	static const String highway_svg = 'assets/vectors/highway.svg';

	static const String icon_chevron_left_x2_svg = 'assets/vectors/icon_chevron_left_x2.svg';

	static const String icon_mobile_signal_1_x2_svg = 'assets/vectors/icon_mobile_signal_1_x2.svg';

	static const String icon_mobile_signal_x2_svg = 'assets/vectors/icon_mobile_signal_x2.svg';

	static const String ic_search_1_x2_svg = 'assets/vectors/ic_search_1_x2.svg';

	static const String ic_search_x2_svg = 'assets/vectors/ic_search_x2.svg';

	static const String image_1_x2_svg = 'assets/vectors/image_1_x2.svg';

	static const String image_2_x2_svg = 'assets/vectors/image_2_x2.svg';

	static const String image_3_x2_svg = 'assets/vectors/image_3_x2.svg';

	static const String image_4_x2_svg = 'assets/vectors/image_4_x2.svg';

	static const String image_5_x2_svg = 'assets/vectors/image_5_x2.svg';

	static const String image_x2_svg = 'assets/vectors/image_x2.svg';

	static const String line_11_x2_svg = 'assets/vectors/line_11_x2.svg';

	static const String line_12_x2_svg = 'assets/vectors/line_12_x2.svg';

	static const String line_13_x2_svg = 'assets/vectors/line_13_x2.svg';

	static const String line_14_x2_svg = 'assets/vectors/line_14_x2.svg';

	static const String line_15_x2_svg = 'assets/vectors/line_15_x2.svg';

	static const String line_1_x2_svg = 'assets/vectors/line_1_x2.svg';

	static const String line_201_x2_svg = 'assets/vectors/line_201_x2.svg';

	static const String line_20_x2_svg = 'assets/vectors/line_20_x2.svg';

	static const String line_21_x2_svg = 'assets/vectors/line_21_x2.svg';

	static const String line_22_x2_svg = 'assets/vectors/line_22_x2.svg';

	static const String line_23_x2_svg = 'assets/vectors/line_23_x2.svg';

	static const String line_24_x2_svg = 'assets/vectors/line_24_x2.svg';

	static const String line_25_x2_svg = 'assets/vectors/line_25_x2.svg';

	static const String line_2_x2_svg = 'assets/vectors/line_2_x2.svg';

	static const String line_31_x2_svg = 'assets/vectors/line_31_x2.svg';

	static const String line_32_x2_svg = 'assets/vectors/line_32_x2.svg';

	static const String line_33_x2_svg = 'assets/vectors/line_33_x2.svg';

	static const String line_34_x2_svg = 'assets/vectors/line_34_x2.svg';

	static const String line_35_x2_svg = 'assets/vectors/line_35_x2.svg';

	static const String line_3_x2_svg = 'assets/vectors/line_3_x2.svg';

	static const String line_41_x2_svg = 'assets/vectors/line_41_x2.svg';

	static const String line_42_x2_svg = 'assets/vectors/line_42_x2.svg';

	static const String line_43_x2_svg = 'assets/vectors/line_43_x2.svg';

	static const String line_44_x2_svg = 'assets/vectors/line_44_x2.svg';

	static const String line_45_x2_svg = 'assets/vectors/line_45_x2.svg';

	static const String line_4_x2_svg = 'assets/vectors/line_4_x2.svg';

	static const String lock_key_1_x2_svg = 'assets/vectors/lock_key_1_x2.svg';

	static const String lock_key_x2_svg = 'assets/vectors/lock_key_x2.svg';

	static const String map_1_x2_svg = 'assets/vectors/map_1_x2.svg';

	static const String map_x2_svg = 'assets/vectors/map_x2.svg';

	static const String mask_1_x2_svg = 'assets/vectors/mask_1_x2.svg';

	static const String mask_2_x2_svg = 'assets/vectors/mask_2_x2.svg';

	static const String mask_3_x2_svg = 'assets/vectors/mask_3_x2.svg';

	static const String mask_4_x2_svg = 'assets/vectors/mask_4_x2.svg';

	static const String mask_5_x2_svg = 'assets/vectors/mask_5_x2.svg';

	static const String mask_6_x2_svg = 'assets/vectors/mask_6_x2.svg';

	static const String mask_7_x2_svg = 'assets/vectors/mask_7_x2.svg';

	static const String mask_group_x2_svg = 'assets/vectors/mask_group_x2.svg';

	static const String mask_x2_svg = 'assets/vectors/mask_x2.svg';

	static const String mastercard_loho_1_x2_svg = 'assets/vectors/mastercard_loho_1_x2.svg';

	static const String mastercard_loho_2_x2_svg = 'assets/vectors/mastercard_loho_2_x2.svg';

	static const String mastercard_loho_3_x2_svg = 'assets/vectors/mastercard_loho_3_x2.svg';

	static const String mastercard_loho_4_x2_svg = 'assets/vectors/mastercard_loho_4_x2.svg';

	static const String mastercard_loho_5_x2_svg = 'assets/vectors/mastercard_loho_5_x2.svg';

	static const String mastercard_loho_x2_svg = 'assets/vectors/mastercard_loho_x2.svg';

	static const String mobile_signal_2_x2_svg = 'assets/vectors/mobile_signal_2_x2.svg';

	static const String mobile_signal_x2_svg = 'assets/vectors/mobile_signal_x2.svg';

	static const String navigation_10_x2_svg = 'assets/vectors/navigation_10_x2.svg';

	static const String navigation_11_x2_svg = 'assets/vectors/navigation_11_x2.svg';

	static const String navigation_12_x2_svg = 'assets/vectors/navigation_12_x2.svg';

	static const String navigation_13_x2_svg = 'assets/vectors/navigation_13_x2.svg';

	static const String navigation_14_x2_svg = 'assets/vectors/navigation_14_x2.svg';

	static const String navigation_15_x2_svg = 'assets/vectors/navigation_15_x2.svg';

	static const String navigation_16_x2_svg = 'assets/vectors/navigation_16_x2.svg';

	static const String navigation_17_x2_svg = 'assets/vectors/navigation_17_x2.svg';

	static const String navigation_18_x2_svg = 'assets/vectors/navigation_18_x2.svg';

	static const String navigation_1_x2_svg = 'assets/vectors/navigation_1_x2.svg';

	static const String navigation_2_x2_svg = 'assets/vectors/navigation_2_x2.svg';

	static const String navigation_3_x2_svg = 'assets/vectors/navigation_3_x2.svg';

	static const String navigation_4_x2_svg = 'assets/vectors/navigation_4_x2.svg';

	static const String navigation_5_x2_svg = 'assets/vectors/navigation_5_x2.svg';

	static const String navigation_6_x2_svg = 'assets/vectors/navigation_6_x2.svg';

	static const String navigation_7_x2_svg = 'assets/vectors/navigation_7_x2.svg';

	static const String navigation_8_x2_svg = 'assets/vectors/navigation_8_x2.svg';

	static const String navigation_9_x2_svg = 'assets/vectors/navigation_9_x2.svg';

	static const String navigation_x2_svg = 'assets/vectors/navigation_x2.svg';

	static const String notch_1_x2_svg = 'assets/vectors/notch_1_x2.svg';

	static const String notch_x2_svg = 'assets/vectors/notch_x2.svg';

	static const String noun_send_3612583110_x2_svg = 'assets/vectors/noun_send_3612583110_x2.svg';

	static const String noun_send_3612583111_x2_svg = 'assets/vectors/noun_send_3612583111_x2.svg';

	static const String noun_send_361258311_x2_svg = 'assets/vectors/noun_send_361258311_x2.svg';

	static const String noun_send_361258312_x2_svg = 'assets/vectors/noun_send_361258312_x2.svg';

	static const String noun_send_361258313_x2_svg = 'assets/vectors/noun_send_361258313_x2.svg';

	static const String noun_send_361258314_x2_svg = 'assets/vectors/noun_send_361258314_x2.svg';

	static const String noun_send_361258315_x2_svg = 'assets/vectors/noun_send_361258315_x2.svg';

	static const String noun_send_361258316_x2_svg = 'assets/vectors/noun_send_361258316_x2.svg';

	static const String noun_send_361258317_x2_svg = 'assets/vectors/noun_send_361258317_x2.svg';

	static const String noun_send_361258318_x2_svg = 'assets/vectors/noun_send_361258318_x2.svg';

	static const String noun_send_361258319_x2_svg = 'assets/vectors/noun_send_361258319_x2.svg';

	static const String noun_send_36125831_x2_svg = 'assets/vectors/noun_send_36125831_x2.svg';

	static const String path_1_x2_svg = 'assets/vectors/path_1_x2.svg';

	static const String path_2_x2_svg = 'assets/vectors/path_2_x2.svg';

	static const String path_3_x2_svg = 'assets/vectors/path_3_x2.svg';

	static const String path_4_x2_svg = 'assets/vectors/path_4_x2.svg';

	static const String path_5_x2_svg = 'assets/vectors/path_5_x2.svg';

	static const String path_x2_svg = 'assets/vectors/path_x2.svg';

	static const String rectangle_104_x2_svg = 'assets/vectors/rectangle_104_x2.svg';

	static const String rectangle_1_x2_svg = 'assets/vectors/rectangle_1_x2.svg';

	static const String rectangle_2_x2_svg = 'assets/vectors/rectangle_2_x2.svg';

	static const String rectangle_35_x2_svg = 'assets/vectors/rectangle_35_x2.svg';

	static const String rectangle_39_x2_svg = 'assets/vectors/rectangle_39_x2.svg';

	static const String rectangle_3_x2_svg = 'assets/vectors/rectangle_3_x2.svg';

	static const String rectangle_43_x2_svg = 'assets/vectors/rectangle_43_x2.svg';

	static const String rectangle_46_x2_svg = 'assets/vectors/rectangle_46_x2.svg';

	static const String rectangle_4_x2_svg = 'assets/vectors/rectangle_4_x2.svg';

	static const String rectangle_50_x2_svg = 'assets/vectors/rectangle_50_x2.svg';

	static const String rectangle_72_x2_svg = 'assets/vectors/rectangle_72_x2.svg';

	static const String rectangle_76_x2_svg = 'assets/vectors/rectangle_76_x2.svg';

	static const String rectangle_79_x2_svg = 'assets/vectors/rectangle_79_x2.svg';

	static const String rectangle_83_x2_svg = 'assets/vectors/rectangle_83_x2.svg';

	static const String rectangle_86_x2_svg = 'assets/vectors/rectangle_86_x2.svg';

	static const String rectangle_87_x2_svg = 'assets/vectors/rectangle_87_x2.svg';

	static const String rectangle_88_x2_svg = 'assets/vectors/rectangle_88_x2.svg';

	static const String rectangle_90_x2_svg = 'assets/vectors/rectangle_90_x2.svg';

	static const String rectangle_93_x2_svg = 'assets/vectors/rectangle_93_x2.svg';

	static const String rectangle_97_x2_svg = 'assets/vectors/rectangle_97_x2.svg';

	static const String scan_1_x2_svg = 'assets/vectors/scan_1_x2.svg';

	static const String scan_2_x2_svg = 'assets/vectors/scan_2_x2.svg';

	static const String scan_3_x2_svg = 'assets/vectors/scan_3_x2.svg';

	static const String scan_4_x2_svg = 'assets/vectors/scan_4_x2.svg';

	static const String scan_5_x2_svg = 'assets/vectors/scan_5_x2.svg';

	static const String scan_x2_svg = 'assets/vectors/scan_x2.svg';

	static const String sf_symbol_xmark_x2_svg = 'assets/vectors/sf_symbol_xmark_x2.svg';

	static const String shape_x2_svg = 'assets/vectors/shape_x2.svg';

	static const String sign_board_x2_svg = 'assets/vectors/sign_board_x2.svg';

	static const String sliders_horizontal_1_x2_svg = 'assets/vectors/sliders_horizontal_1_x2.svg';

	static const String sliders_horizontal_2_x2_svg = 'assets/vectors/sliders_horizontal_2_x2.svg';

	static const String sliders_horizontal_3_x2_svg = 'assets/vectors/sliders_horizontal_3_x2.svg';

	static const String sliders_horizontal_4_x2_svg = 'assets/vectors/sliders_horizontal_4_x2.svg';

	static const String sliders_horizontal_5_x2_svg = 'assets/vectors/sliders_horizontal_5_x2.svg';

	static const String sliders_horizontal_6_x2_svg = 'assets/vectors/sliders_horizontal_6_x2.svg';

	static const String sliders_horizontal_7_x2_svg = 'assets/vectors/sliders_horizontal_7_x2.svg';

	static const String status_bar_battery_1_x2_svg = 'assets/vectors/status_bar_battery_1_x2.svg';

	static const String status_bar_battery_x2_svg = 'assets/vectors/status_bar_battery_x2.svg';

	static const String subtract_1_x2_svg = 'assets/vectors/subtract_1_x2.svg';

	static const String subtract_2_x2_svg = 'assets/vectors/subtract_2_x2.svg';

	static const String subtract_3_x2_svg = 'assets/vectors/subtract_3_x2.svg';

	static const String subtract_4_x2_svg = 'assets/vectors/subtract_4_x2.svg';

	static const String subtract_5_x2_svg = 'assets/vectors/subtract_5_x2.svg';

	static const String subtract_stroke_1_x2_svg = 'assets/vectors/subtract_stroke_1_x2.svg';

	static const String subtract_stroke_2_x2_svg = 'assets/vectors/subtract_stroke_2_x2.svg';

	static const String subtract_stroke_3_x2_svg = 'assets/vectors/subtract_stroke_3_x2.svg';

	static const String subtract_stroke_x2_svg = 'assets/vectors/subtract_stroke_x2.svg';

	static const String subtract_x2_svg = 'assets/vectors/subtract_x2.svg';

	static const String undraw_design_components_9_vy_61_x2_svg = 'assets/vectors/undraw_design_components_9_vy_61_x2.svg';

	static const String user_2_x2_svg = 'assets/vectors/user_2_x2.svg';

	static const String user_x2_svg = 'assets/vectors/user_x2.svg';

	static const String vector_10_x2_svg = 'assets/vectors/vector_10_x2/svg';

	static const String vector_11_x2_svg = 'assets/vectors/vector_11_x2/svg';

	static const String vector_12_x2_svg = 'assets/vectors/vector_12_x2/svg';

	static const String vector_13_x2_svg = 'assets/vectors/vector_13_x2/svg';

	static const String vector_14_x2_svg = 'assets/vectors/vector_14_x2/svg';

	static const String vector_15_x2_svg = 'assets/vectors/vector_15_x2/svg';

	static const String vector_16_x2_svg = 'assets/vectors/vector_16_x2/svg';

	static const String vector_17_x2_svg = 'assets/vectors/vector_17_x2/svg';

	static const String vector_18_x2_svg = 'assets/vectors/vector_18_x2/svg';

	static const String vector_19_x2_svg = 'assets/vectors/vector_19_x2/svg';

	static const String vector_1_x2_svg = 'assets/vectors/vector_1_x2/svg';

	static const String vector_20_x2_svg = 'assets/vectors/vector_20_x2/svg';

	static const String vector_21_x2_svg = 'assets/vectors/vector_21_x2/svg';

	static const String vector_2_x2_svg = 'assets/vectors/vector_2_x2/svg';

	static const String vector_3_x2_svg = 'assets/vectors/vector_3_x2/svg';

	static const String vector_4_x2_svg = 'assets/vectors/vector_4_x2/svg';

	static const String vector_5_x2_svg = 'assets/vectors/vector_5_x2/svg';

	static const String vector_6_x2_svg = 'assets/vectors/vector_6_x2/svg';

	static const String vector_7_x2_svg = 'assets/vectors/vector_7_x2/svg';

	static const String vector_8_x2_svg = 'assets/vectors/vector_8_x2/svg';

	static const String vector_9_x2_svg = 'assets/vectors/vector_9_x2/svg';

	static const String wallet_1_x2_svg = 'assets/vectors/wallet_1_x2.svg';

	static const String wallet_2_x2_svg = 'assets/vectors/wallet_2_x2.svg';

	static const String wallet_3_x2_svg = 'assets/vectors/wallet_3_x2.svg';

	static const String wallet_4_x2_svg = 'assets/vectors/wallet_4_x2.svg';

	static const String wallet_5_x2_svg = 'assets/vectors/wallet_5_x2.svg';

	static const String wallet_x2_svg = 'assets/vectors/wallet_x2.svg';

	static const String wifi_10_x2_svg = 'assets/vectors/wifi_10_x2.svg';

	static const String wifi_11_x2_svg = 'assets/vectors/wifi_11_x2.svg';

	static const String wifi_12_x2_svg = 'assets/vectors/wifi_12_x2.svg';

	static const String wifi_13_x2_svg = 'assets/vectors/wifi_13_x2.svg';

	static const String wifi_14_x2_svg = 'assets/vectors/wifi_14_x2.svg';

	static const String wifi_15_x2_svg = 'assets/vectors/wifi_15_x2.svg';

	static const String wifi_16_x2_svg = 'assets/vectors/wifi_16_x2.svg';

	static const String wifi_18_x2_svg = 'assets/vectors/wifi_18_x2.svg';

	static const String wifi_19_x2_svg = 'assets/vectors/wifi_19_x2.svg';

	static const String wifi_1_x2_svg = 'assets/vectors/wifi_1_x2.svg';

	static const String wifi_20_x2_svg = 'assets/vectors/wifi_20_x2.svg';

	static const String wifi_21_x2_svg = 'assets/vectors/wifi_21_x2.svg';

	static const String wifi_22_x2_svg = 'assets/vectors/wifi_22_x2.svg';

	static const String wifi_23_x2_svg = 'assets/vectors/wifi_23_x2.svg';

	static const String wifi_24_x2_svg = 'assets/vectors/wifi_24_x2.svg';

	static const String wifi_25_x2_svg = 'assets/vectors/wifi_25_x2.svg';

	static const String wifi_2_x2_svg = 'assets/vectors/wifi_2_x2.svg';

	static const String wifi_3_x2_svg = 'assets/vectors/wifi_3_x2.svg';

	static const String wifi_4_x2_svg = 'assets/vectors/wifi_4_x2.svg';

	static const String wifi_5_x2_svg = 'assets/vectors/wifi_5_x2.svg';

	static const String wifi_6_x2_svg = 'assets/vectors/wifi_6_x2.svg';

	static const String wifi_7_x2_svg = 'assets/vectors/wifi_7_x2.svg';

	static const String wifi_8_x2_svg = 'assets/vectors/wifi_8_x2.svg';

	static const String wifi_9_x2_svg = 'assets/vectors/wifi_9_x2.svg';

	static const String xmlid_5171_x2_svg = 'assets/vectors/xmlid_5171_x2.svg';

	static const String xmlid_517_x2_svg = 'assets/vectors/xmlid_517_x2.svg';

}
